name: AI Auto Code Generator

on:
  workflow_dispatch:
    inputs:
      instruction:
        description: 'What code do you want to generate?'
        required: true
        default: 'Create Express route /status'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Code with ChatGPT
        run: |
          echo "Calling ChatGPT API..."
          RESPONSE=$(curl https://api.openai.com/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [{"role": "user", "content": "${{ github.event.inputs.instruction }}"}],
              "temperature": 0.2
            }' | jq -r '.choices[0].message.content')

          echo "$RESPONSE" > generated_code.js
          echo "Generated code written to generated_code.js"

      - name: Commit Generated Code
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add generated_code.js
          git commit -m "Auto-generated real code using ChatGPT API"
          git push
